### PR TITLE
Team 'yolo is so 2013' Test Program (plus the rest of our repo)

### PR DESCRIPTION
**Pull request by jenwei**
Wasn't sure how to submit a PR of just the test program folder with the test code and readme.

### CODE REVIEW

**Comment by benthill** [comment]
Sorry, can't take this pull request as is since it would pull EVERYTHING into the class repo.

Check out https://piazza.com/class/ie4a5pppecd1yp?cid=131

**Comment by jenwei** [comment]
Sounds good - we were having issues creating a new branch off the master class repo, but we might've found a work-around. If not, we may resort to emailing you the files.

**Comment by benthill** [comment]
No worries, email is perfectly fine for this one. I realize it was trickier
than I thought and I don't want people to be nervous about losing work, so
I should have done a quick walkthrough in class. Thank you for your Piazza
question!

-Ben

**Comment by jenwei** [comment]
Found a way around it!

Create a new branch off the master class repo
`git checkout -b [name of new branch]`
`git reset --hard benthill/master`

Use `cherry-pick` if there are individual commits made for the test program and readme. Otherwise, switch to `master`, save a copy of the team folder on your desktop, switch back to your `[name of new branch` branch, and copy it into the `asmtest` folder. The second option is a bit more tedious, but it's at least easier and less error-prone.

**Comment by benthill** [comment]
Awesome! Pull request applied.

Feel free to add to the answer on Piazza if you like to help the other
students. The one thing to be careful of here (and that you should warn
about if you suggest this to other teams) is that with git reset --hard you
can potentially lose work if you have not been diligent about actually
committing everything to your repo.

**Comment by jenwei** [comment]
Will do - thanks!

**Pull request closed without merging**
